### ISSUE TITLE
Blocks changing once placed

### ISSUE THREAD

**Issue by mminidot23** [cubedcommunity/CubedTextures#12]
Whenever I place shelves they turn into cupboards after a few seconds and when I place any of the sofa parts they turn into mailboxes and shop signs. 

![image](https://user-images.githubusercontent.com/67300126/85351662-24594100-b4b9-11ea-9f8e-aa05c47a98c3.jpeg)

![image](https://user-images.githubusercontent.com/67300126/85351670-291df500-b4b9-11ea-9b46-759a686c7a1d.jpeg)

![image](https://user-images.githubusercontent.com/67300126/85351677-2e7b3f80-b4b9-11ea-889f-7afe821786f7.jpeg)

![image](https://user-images.githubusercontent.com/67300126/85351684-31763000-b4b9-11ea-9993-d7199fbd249c.jpeg)

**Comment by MaiXReo** [comment]
That is because those are corals, and corals die if they dont have water, so they turn into dead coral models. you need some mod or plugin to keep corals alive.
