### ISSUE TITLE
5.0.2.2 Leaves do not have textures

### ISSUE THREAD

**Issue by SanchitGoel0206** [cubedcommunity/CubedTextures#13]
Acacia, birch, dark oak, and oak leaves all have textures that don't work as they are 1x1 pixels in dimensions in the block textures folder. They show up as invisible in game while jungle and spruce textures work as they have texture pngs in folder. Below the files are attached, however they are barely visible because of their size. 

![acacia_leaves](https://user-images.githubusercontent.com/68081897/104660285-10567600-567b-11eb-9127-689706b7e6e0.png)
![birch_leaves](https://user-images.githubusercontent.com/68081897/104660281-0fbddf80-567b-11eb-8c82-8d9b5de0edd5.png)
![dark_oak_leaves](https://user-images.githubusercontent.com/68081897/104660283-10567600-567b-11eb-80ee-d7e3f6e0852a.png)
![oak_leaves](https://user-images.githubusercontent.com/68081897/104660284-10567600-567b-11eb-8135-b686e631de34.png)

**Comment by Aequotis** [comment]
Please check you have Optifine Mod installed, and leaves set to fancy. This is an intentional feature to allow 3D leaves which can be changed based on biome.
