### ISSUE TITLE
grass texture invisible when snow is on top of the block 

### ISSUE THREAD

**Issue by toast411** [cubedcommunity/CubedTextures#15]
Grass is invisible when snow is on top of it

![2021-09-13_21 01 46](https://user-images.githubusercontent.com/90651197/133150170-b2bab0a1-b0c6-493d-8368-21bb283d7edd.png)

im on minecraft ver 1.13.2 optifine
resource pack ver ver 5.0.2.2

**Comment by Aequotis** [comment]
Fixed in 1.14.4 release
