### ISSUE TITLE
5.0.0 flickering vine textures against blocks

### ISSUE THREAD

**Issue by Aequotis** [cubedcommunity/CubedTextures#7]
**Describe the bug**
The base layer of vines (against a block) needs moving forward a bit as its clipping with blocks.

**To Reproduce**
1. Place vines against a block
2. Step back around 15 blocks to see flickering

**Screenshots**

![image](https://user-images.githubusercontent.com/42449924/79044268-0f7c4980-7bfc-11ea-8e1f-95e636cc4d32.png)

**Comment by taraago** [comment]
fixed
